### ISSUE TITLE
Task list for revamped Revision 3

### ISSUE THREAD

**Issue by PT400C** [Jomcraft-Network/DefaultSettings#3]
- [ ] Custom versionchecker (+changelog) and better version outputs in about section
- [ ] Command cleanup and extension
  - [ ] Add proper documentation here on GitLab for the commands

**Comment by PT400C** [comment]
Planned for future versions/revisions:

- [ ] Custom versionchecker (+changelog) and better version outputs in about section
- [ ] Reintroduce the DS custom GUI
- [ ] implement preprocessor to effortlessly support various game versions
